### creates a new patient record
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "John Doe 1",
    "email": "test@mail.com",
    "address": "123 Main St, Anytown, USA",
    "DOB": "2001-01-01",
  "RegisterDate": "2024-06-15"
}
###